export const CHUO_SOBU_COLOR = "#FFD400";
export const CHUO_SOBU_RAILWAY = "ChuoSobuLocal";

export const CHUO_SOBU_STATIONS = [
  { id: "Mitaka", code: "JB01", ja: "三鷹", ko: "미타카", en: "Mitaka" },
  {
    id: "Kichijoji",
    code: "JB02",
    ja: "吉祥寺",
    ko: "기치조지",
    en: "Kichijoji",
  },
  {
    id: "NishiOgikubo",
    code: "JB03",
    ja: "西荻窪",
    ko: "니시오기쿠보",
    en: "Nishi-Ogikubo",
  },
  { id: "Ogikubo", code: "JB04", ja: "荻窪", ko: "오기쿠보", en: "Ogikubo" },
  {
    id: "Asagaya",
    code: "JB05",
    ja: "阿佐ケ谷",
    ko: "아사가야",
    en: "Asagaya",
  },
  { id: "Koenji", code: "JB06", ja: "高円寺", ko: "고엔지", en: "Koenji" },
  { id: "Nakano", code: "JB07", ja: "中野", ko: "나카노", en: "Nakano" },
  {
    id: "HigashiNakano",
    code: "JB08",
    ja: "東中野",
    ko: "히가시나카노",
    en: "Higashi-Nakano",
  },
  { id: "Okubo", code: "JB09", ja: "大久保", ko: "오쿠보", en: "Okubo" },
  { id: "Shinjuku", code: "JB10", ja: "新宿", ko: "신주쿠", en: "Shinjuku" },
  { id: "Yoyogi", code: "JB11", ja: "代々木", ko: "요요기", en: "Yoyogi" },
  {
    id: "Sendagaya",
    code: "JB12",
    ja: "千駄ケ谷",
    ko: "센다가야",
    en: "Sendagaya",
  },
  {
    id: "Shinanomachi",
    code: "JB13",
    ja: "信濃町",
    ko: "시나노마치",
    en: "Shinanomachi",
  },
  { id: "Yotsuya", code: "JB14", ja: "四ツ谷", ko: "요쓰야", en: "Yotsuya" },
  {
    id: "Ichigaya",
    code: "JB15",
    ja: "市ケ谷",
    ko: "이치가야",
    en: "Ichigaya",
  },
  {
    id: "Iidabashi",
    code: "JB16",
    ja: "飯田橋",
    ko: "이다바시",
    en: "Iidabashi",
  },
  {
    id: "Suidobashi",
    code: "JB17",
    ja: "水道橋",
    ko: "스이도바시",
    en: "Suidobashi",
  },
  {
    id: "Ochanomizu",
    code: "JB18",
    ja: "御茶ノ水",
    ko: "오차노미즈",
    en: "Ochanomizu",
  },
  {
    id: "Akihabara",
    code: "JB19",
    ja: "秋葉原",
    ko: "아키하바라",
    en: "Akihabara",
  },
  {
    id: "Asakusabashi",
    code: "JB20",
    ja: "浅草橋",
    ko: "아사쿠사바시",
    en: "Asakusabashi",
  },
  { id: "Ryogoku", code: "JB21", ja: "両国", ko: "료고쿠", en: "Ryogoku" },
  {
    id: "Kinshicho",
    code: "JB22",
    ja: "錦糸町",
    ko: "긴시초",
    en: "Kinshicho",
  },
  { id: "Kameido", code: "JB23", ja: "亀戸", ko: "가메이도", en: "Kameido" },
  { id: "Hirai", code: "JB24", ja: "平井", ko: "히라이", en: "Hirai" },
  {
    id: "ShinKoiwa",
    code: "JB25",
    ja: "新小岩",
    ko: "신코이와",
    en: "Shin-Koiwa",
  },
  { id: "Koiwa", code: "JB26", ja: "小岩", ko: "코이와", en: "Koiwa" },
  { id: "Ichikawa", code: "JB27", ja: "市川", ko: "이치카와", en: "Ichikawa" },
  {
    id: "Motoyawata",
    code: "JB28",
    ja: "本八幡",
    ko: "모토야와타",
    en: "Motoyawata",
  },
  {
    id: "ShimosaNakayama",
    code: "JB29",
    ja: "下総中山",
    ko: "시모사나카야마",
    en: "Shimosa-Nakayama",
  },
  {
    id: "NishiFunabashi",
    code: "JB30",
    ja: "西船橋",
    ko: "니시후나바시",
    en: "Nishi-Funabashi",
  },
  {
    id: "Funabashi",
    code: "JB31",
    ja: "船橋",
    ko: "후나바시",
    en: "Funabashi",
  },
  {
    id: "HigashiFunabashi",
    code: "JB32",
    ja: "東船橋",
    ko: "히가시후나바시",
    en: "Higashi-Funabashi",
  },
  {
    id: "Tsudanuma",
    code: "JB33",
    ja: "津田沼",
    ko: "쓰다누마",
    en: "Tsudanuma",
  },
  {
    id: "MakuhariHongo",
    code: "JB34",
    ja: "幕張本郷",
    ko: "마쿠하리혼고",
    en: "Makuhari-Hongo",
  },
  { id: "Makuhari", code: "JB35", ja: "幕張", ko: "마쿠하리", en: "Makuhari" },
  {
    id: "ShinKemigawa",
    code: "JB36",
    ja: "新検見川",
    ko: "신케미가와",
    en: "Shin-Kemigawa",
  },
  { id: "Inage", code: "JB37", ja: "稲毛", ko: "이나게", en: "Inage" },
  {
    id: "NishiChiba",
    code: "JB38",
    ja: "西千葉",
    ko: "니시치바",
    en: "Nishi-Chiba",
  },
  { id: "Chiba", code: "JB39", ja: "千葉", ko: "지바", en: "Chiba" },
] as const;

export type ChuoSobuStation = (typeof CHUO_SOBU_STATIONS)[number];
